### PR TITLE
fix: modify patch issue

### PR DESCRIPTION
**Pull request by wep21**
I updated patch for tvm v0.8.0 and modified multiple patch apply.

### CODE REVIEW

**Comment by wep21** [comment]
@nuclearsandwich https://build.ros2.org/job/Rdev__tvm_vendor__ubuntu_jammy_amd64/3/console
The build process on ros2 ci still failed, but I can't reproduce the problem on my local environment. Is there any way to reproduce the issue in the environment equivalent to ros2 ci?

**Comment by nuclearsandwich** [comment]
Yes. Although getting "into" the reproduction environment involves a bit of prying. 

Just about every job on the build farm is reproducable on any Linux system that has python3 and Docker installed (and you'll need the [ros_buildfarm](https://github.com/ros-infrastructure/ros_builfdarm) scripts somewhere for bootstrapping.

My usual workflow is
1. Install the latest commit of ros_buildfarm into a virtualenv somewhere:
`pip install git+https://github.com/ros-infrastructure/ros_buildfarm`
2. Set up a tempdir to house the build.
`mkdir /tmp/tvm_vendor`
3. Use `generate_release_script.py` to generate a release script.
```
generate_release_script.py \
  https://raw.githubusercontent.com/ros2/ros_buildfarm_config/ros2/index.yaml \
  rolling default tvm_vendor ubuntu jammy amd64 > /tmp/tvm_vendor/run.sh
```
4. Run the script as-is to validate that you get _the same_ failure as the buildfarm instead of a different one.
`cd /tmp/tvm_vendor && sh run.sh`

5. Assuming that you do, it's time to tweak the build to let you pry into the container.
By default the docker containers are removed once they finish running using the `--rm` flag to docker-run. I usually edit the script to remove the `--rm` flag from the final `docker run` invocation in the script which is the container that builds the binarydeb so that container will persist after the build fails.

6. Then clean up the directories created by the previous run and run the script again.
After it finishes, `docker ps -a` will list it as the most recently exited container.
This is where it Ges Weird:tm:. Restarting the container will also restart the python script within it that will run the build, fail, and then exit... closing the container. So we want that script to stop but we can't restart the container without it. (an alternative to getting weird is running our own container copying the docker run arguments from the script but I started doing it this way and so far I've been too stubborn to change. Note the container name or ID. I'll use CID to refer to it below.
```
docker restart CID && docker exec -u root CID pkill -STOP python3
```

7. Now that the container is restarted and the python process running the automated build has been paused, we can tool around in the container and try things out.
```
docker exec -ti uroot CID bash
```

8. Since the package contents are bind-mounted from the host system, you can tweak and edit from the host and just re-run builds from the container. It isn't possible to re-run the entire generated script with customized package contents because the script will re-fetch and override the local contents when doing a complete run.

**Comment by wep21** [comment]
@nuclearsandwich Thank you for your detailed explanation. I found out that the issue was multiple patch apply
in external project add.

**Review by ambroise-arm — APPROVED** [review]
looks good to me
Thanks for also updating the patch files!

**Pull request merged**
